# -*- coding: utf-8 -*-
"""lab9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XDRcOoX7N8AyV2CtQvZ2yk4vz_w3GDld
"""

!pip install scikit-learn pandas numpy matplotlib seaborn -q

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
from sklearn.metrics import (silhouette_score, calinski_harabasz_score,
                             davies_bouldin_score)



iris = load_iris()
df_full = pd.DataFrame(iris.data, columns=iris.feature_names)
df_full['target'] = iris.target
df_full['target_name'] = [iris.target_names[t] for t in iris.target]

print("=== Датасет Iris ===")
print(df_full.head(10))
print(f"\nРазмер: {df_full.shape}")
print(f"\nПризнаки: {iris.feature_names}")
print(f"Классы: {iris.target_names}")
print(f"\nОписательная статистика:")
print(df_full.describe())


# D1 — 4 числовых признака без целевой переменной
D1 = df_full[iris.feature_names].values
true_labels = iris.target

# Стандартизация
scaler = StandardScaler()
D1_scaled = scaler.fit_transform(D1)

print(f"\n=== Датасет D1 ===")
print(f"Форма: {D1_scaled.shape}")
print(f"Признаков: {D1_scaled.shape[1]} (sepal length, sepal width, "
      f"petal length, petal width)")



pca = PCA(n_components=2, random_state=42)
D2 = pca.fit_transform(D1_scaled)

print(f"\n=== Датасет D2 (PCA) ===")
print(f"Форма: {D2.shape}")
print(f"Объяснённая дисперсия: {pca.explained_variance_ratio_}")
print(f"Суммарная объяснённая дисперсия: "
      f"{pca.explained_variance_ratio_.sum():.4f}")


tsne = TSNE(n_components=2, random_state=42, perplexity=30,
            n_iter=1000)
D3 = tsne.fit_transform(D1_scaled)

print(f"\n=== Датасет D3 (t-SNE) ===")
print(f"Форма: {D3.shape}")


colors = ['#e05c6b', '#7ee8a2', '#4ecdc4']
class_names = iris.target_names

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Снижение размерности: PCA vs t-SNE',
             fontsize=14, fontweight='bold')

for ax, D, title in zip(axes, [D2, D3], ['D2 — PCA', 'D3 — t-SNE']):
    for i, name in enumerate(class_names):
        mask = true_labels == i
        ax.scatter(D[mask, 0], D[mask, 1],
                   c=colors[i], label=name,
                   alpha=0.8, edgecolors='white',
                   linewidths=0.3, s=60)
    ax.set_title(title, fontsize=13, fontweight='bold')
    ax.legend()
    ax.set_xlabel('Компонента 1')
    ax.set_ylabel('Компонента 2')
    ax.grid(alpha=0.3)

plt.tight_layout()
plt.savefig('dim_reduction.png', dpi=150, bbox_inches='tight')
plt.show()



N_CLUSTERS = 3

datasets = {
    'D1 (исходный, 4 признака)': D1_scaled,
    'D2 (PCA, 2 компоненты)':    D2,
    'D3 (t-SNE, 2 компоненты)':  D3,
}

methods = {
    'K-Means':       KMeans(n_clusters=N_CLUSTERS, random_state=42,
                            n_init=10),
    'DBSCAN':        DBSCAN(eps=0.5, min_samples=5),
    'Агломеративная': AgglomerativeClustering(n_clusters=N_CLUSTERS,
                                              linkage='ward'),
}

# Таблица результатов
results = []

for ds_name, D in datasets.items():
    for method_name, model in methods.items():
        # Для DBSCAN подбираем eps под размерность
        if method_name == 'DBSCAN':
            eps = 0.5 if D.shape[1] == 4 else 1.5
            model = DBSCAN(eps=eps, min_samples=5)

        labels = model.fit_predict(D)
        n_clusters_found = len(set(labels)) - (1 if -1 in labels else 0)

        # Метрики считаем только если кластеров > 1
        if n_clusters_found > 1:
            sil  = silhouette_score(D, labels)
            ch   = calinski_harabasz_score(D, labels)
            db   = davies_bouldin_score(D, labels)
        else:
            sil, ch, db = None, None, None

        results.append({
            'Датасет':        ds_name,
            'Метод':          method_name,
            'Кластеров':      n_clusters_found,
            'Silhouette':     round(sil, 4) if sil else 'N/A',
            'Calinski-H':     round(ch, 2)  if ch  else 'N/A',
            'Davies-Bouldin': round(db, 4)  if db  else 'N/A',
        })

results_df = pd.DataFrame(results)
print("\n=== Результаты кластеризации ===")
print(results_df.to_string(index=False))



# Рисуем только для D2 и D3 (2D — наглядно)
fig, axes = plt.subplots(2, 3, figsize=(15, 10))
fig.suptitle('Кластеризация датасетов D2 и D3',
             fontsize=14, fontweight='bold')

method_names = list(methods.keys())
ds_2d = [('D2 (PCA)', D2), ('D3 (t-SNE)', D3)]

for row, (ds_name, D) in enumerate(ds_2d):
    for col, method_name in enumerate(method_names):
        ax = axes[row, col]

        if method_name == 'DBSCAN':
            model = DBSCAN(eps=1.5, min_samples=5)
        else:
            model = methods[method_name]

        labels = model.fit_predict(D)
        unique = sorted(set(labels))
        palette = ['#e05c6b', '#7ee8a2', '#4ecdc4',
                   '#f9ca24', '#a29bfe', '#fd79a8']

        for i, lbl in enumerate(unique):
            mask = labels == lbl
            color = '#888888' if lbl == -1 else palette[i % len(palette)]
            name  = 'Шум' if lbl == -1 else f'Кластер {lbl+1}'
            ax.scatter(D[mask, 0], D[mask, 1],
                       c=color, label=name,
                       alpha=0.8, edgecolors='white',
                       linewidths=0.3, s=40)

        n_found = len(set(labels)) - (1 if -1 in labels else 0)

        # Силуэт
        if n_found > 1:
            sil = silhouette_score(D, labels)
            ax.set_title(f'{ds_name}\n{method_name} '
                         f'| Silhouette={sil:.3f}',
                         fontsize=10, fontweight='bold')
        else:
            ax.set_title(f'{ds_name}\n{method_name} | N/A',
                         fontsize=10, fontweight='bold')

        ax.legend(fontsize=7)
        ax.grid(alpha=0.2)
        ax.set_xlabel('Компонента 1')
        ax.set_ylabel('Компонента 2')

plt.tight_layout()
plt.savefig('clustering.png', dpi=150, bbox_inches='tight')
plt.show()



print("\n=== Silhouette Score (чем выше — тем лучше) ===")
pivot_sil = results_df.pivot(index='Датасет',
                              columns='Метод',
                              values='Silhouette')
print(pivot_sil)

print("\n=== Davies-Bouldin (чем ниже — тем лучше) ===")
pivot_db = results_df.pivot(index='Датасет',
                             columns='Метод',
                             values='Davies-Bouldin')
print(pivot_db)

print("\n=== Calinski-Harabasz (чем выше — тем лучше) ===")
pivot_ch = results_df.pivot(index='Датасет',
                             columns='Метод',
                             values='Calinski-H')
print(pivot_ch)